- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/DashRepository.kt
- android/app/src/main/java/app/candash/cluster/DashViewModel.kt
- android/app/src/main/java/app/candash/cluster/FullscreenActivity.kt
- android/app/src/main/java/app/candash/cluster/InfoFragment.kt
- android/app/src/main/java/app/candash/cluster/MockPandaService.kt
- android/app/src/main/java/app/candash/cluster/PandaService.kt
- android/app/src/main/java/app/candash/cluster/PandaServiceImpl.kt
- android/app/src/main/res/drawable/ic_baseline_delete_24.xml
- android/app/src/main/res/layout/fragment_info.xml
The purpose of this is to allow the fragments to specify which signals they want/need.  Later, I'd like to use this to make theming easier -- each theme will be able to specify the signals that it wants.
There are quite a few changes to functionality:
* We weren't every clearing filters before, so this diff includes clearing the filters each time we sent the filters.
* We weren't handling the case where we could have more than 48 filters and need to send them in multiple packets.
* We were starting/stopping the PandaService in the Activity.  Now we will be starting/stopping in each fragment (since we expect they may have different filters from each other).
* Starting/stopping in Fragments exposed an issue where we could get stuck in a while loop waiting for shutdown (when we actually …
> Allows fragments to specify signal filters

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
- android/app/src/main/java/app/candash/cluster/Constants.kt
Original signal used to switch to the charging view is `PCS_hvChargeStatus` which doesn't seem to switch away from 0 on non-SUC DC chargers (at least ones i tested). This PR changes that to `BMS_chargeRequest`, which seems to reliably go from 0 to 1 (with no intermediate or alternate values) when *any* kind of charging is initiated.
Alternative to this might be `CP_chargeCablePresent` if switching to charging view as soon as the connector is plugged in is more desireable. This might actually not be a bad idea, as seeing the green gauge on the screen will remind you the car is still plugged in when getting ready to leave.
This fixes issue #12
> Change chargeStatus from PCS_hvChargeStatus to BMS_chargeRequest

- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/MockCANService.kt
I noticed that when getting out of the car, candash will unhide the blindspot markers, because gearState will change from park to invalid, and the blindspot markers are only hidden while in park.
Additionally, the P would stay highlighted when gear is invalid.
This adds gearInvalid support for gearState, which will ensure blindspot markers stay hidden when the car turns off, and greys out the P as well to indicate the car is off.
> Add gearInvalid to gearState

- android/app/src/main/java/app/candash/cluster/MockCANService.kt
It appears during one of the PR merges a few extra `)` were added, breaking building of the app.
> Fix build error in mock service

- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/SettingsFragment.kt
- android/app/src/main/res/layout/fragment_settings.xml
This is a base branch for the implementation of each of the new options in child branches, to prevent merge conflict hell from adding so many settings in 1 place at the same time.
This also updates the names of preferences to a form where the default value for every preference is false or 0.
- Display Mode = Automatic
- Gauge Mode = Simple
- Show Odo = True
- Show Blindspot = True
- Show Speed Limit = True
- Blackout Screen = False
- Temperature = C
- Power = kW
- Torque = nm
- ensured default settings apply after clearing storage/cache
- ensured settings updated after Save, did not update after Cancel
- ensured existing prefs (forceDarkMode, gaugemode, showodo) still functioned as expected.
(screenshot does not represent default settings)
> Prepare prefs and settings fragment for additional options

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
This implements unit conversion logic for the new unit options added to the settings page; temperature, power, and torque.
Note that the power unit option does not affect the charging power display, it will always show in kW.
Tested using real can data, confirming that each unit option selection correctly displays the correct unit tag and value.
Ensured that it's still possible to change the power unit by tapping the power value at the bottom of the display, in addition to the settings page.
> Add temp, torque, and power unit conversion options

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
This allows for disabling the sonar blindspot arcs for users who don't find them accurate enough to be useful.
They are enabled by default.
Tested via playing back logged can data from a recording in dense traffic:
- reset app by clearing storage and cache, ensured blindspot arcs were visible by default
- unchecked "Show Blindspot Arcs" in settings, ensured they were no longer visible
- checked "Show Blindspot Arcs" in settings, ensure they were visible again.
> Implement blindspot display option

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/MockCANService.kt
This change ensures the display doesn't turn off when the center display turns off while in Drive or Reverse.
This is useful for when rebooting the MCU while driving (it keeps the candash display on)
This only applies to users with the blackout screen preference enabled.
> Never turn off screen while in gear

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
This fixes 2 bugs:
- App launches straight into blackout if not connected to a server (even if blackout feature is disabled)
- blackout must be set to GONE at startup, this line appears to have unintentionally removed in #32 
- App launches into light mode if not connected to a server even though force dark mode is enabled
- if not connected, it never has a isSunUp value to attempt to set the colors, and thus it never has a chance to set it to dark if dark mode is enabled.
> Blackout and darkmode bug fixes

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/PandaService.kt
This uses a known frame (`0x399`) of different lengths to determine which bus is which, this allows us to specify all of our signals on specific buses so we don't get noise from frames of the same ID on the wrong bus, and allows us to remove the custom logic that ignored frames of wrong sizes, etc.
This also includes the busID in the signal lookup so that we can use 2 frames of the same IDs from different buses (if we even have a need to do so).
Now when adding signals, use `Constants.vehicleBus` or `Constants.chassisBus` to specify the bus you expect the signal to be on. It's still possible to specify a signal from `Constants.anyBus` (-1) if you really want to, but is no longer needed and not recommended. It's better to try the bus you think it's on, and view the log for missing signal …
> Automatically determine bus IDs and warn for missing signals

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/MockCANService.kt
- android/app/src/main/java/app/candash/cluster/PandaService.kt
This makes a few key changes:
- if a particular signal hasn't been received in at least 5 seconds, remove that signal from carState (and update flow)
- if we disconnect from a canserver (or mock server stopped), completely clear carState (and update flow)
- add logic to every individual view that if the signal it relies on is `null`, to hide the view (or set it to `""`)
- typically this uses the elvis operator whenever we `.let` a value from carState to run logic only when the value is `null`
- note the importance of avoiding `viewModel.getValue()` since that uses carState *history* which is not cleared
- ...but every view is a bit different, sometimes instead of changing visibility, it was necessary to set the text to empty as other logic would just change the visibility back.
- testing …
> Clear views when a signal goes missing (or disconnected from canserver)

- android/app/src/main/java/app/candash/cluster/PandaService.kt
This fixes the socket closed exception that occurs whenever switching between apps (candash in background) by not trying to send `bye` when already disconnected.
It also reduces the chance of the gauges flickering when coming across transient socket timeouts due to a weak signal or laggy canserver. It does this by shortening the timeout duration, but allowing for multiple timeouts (3) before it clears the carstate data.
Note that while the panda service will stay connected to the canserver for a short time while the app is in the background, the canserver would eventually disconnect candash because it won't see heartbeats while candash is in the background. If you rejoin candash after this, it reconnects very quickly without clearing data.
- while candash is open, stop canserver abruptly, …
> Fix panda service exception when app is in background

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
Updates the can signal to use uSOE which more accurately reflects what the car shows.
Pictures taken at same time:
> Use uSOE for battery level to match car display

- android/app/build.gradle
- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/EfficiencyCalculator.kt
- android/app/src/main/java/app/candash/cluster/SettingsFragment.kt
- android/app/src/main/java/app/candash/cluster/SharedPreferencesExtensions.kt
- android/app/src/main/res/layout/fragment_dash.xml
- android/app/src/main/res/layout/fragment_settings.xml
Allows for tapping the efficiency view to change between Last 5, 15, 30 miles, or 0 (instant). For KM the options are 10, 25, 50, and 0 km.
The instant efficiency is formatted to kWh with 2 decimal places as that value changes extremely rapidly and gets quite large. For historical efficiency it uses whole number Wh units to match the ICE.
The calculation is fairly close to the ICE, it updates faster so it never perfectly matches. The calculation discards any parked consumption/charging, and the history is retained even across app restarts or updates to newer versions.
Here's a video showing the 5 mile range, pending 15 and 30 mile ranges, and instant efficiency (including negative and infinity).
Note there is flickering of the 5 mile range that is only an artifact of how I am playing back …
> Add historical efficiency calculations

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
We discovered that the last frame id from filter request is ignored by s3xy commander, which in the last couple of versions as been the gear selected signal, and commander users noted that the PRND has disappeared. Currently the filter payload is up to 130 bytes, but I suspect (not verified) the commander expects a max 128 bytes as it's a nice round number.
This changes the max filter payload to 127 bytes (42*3+1)
> Decrease max filter count for s3xy commander compatibility

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/MockCANService.kt
- android/app/src/main/res/layout/fragment_dash.xml
This updates the layout to reverse the order of the topmost views (PRND, AP, battery stuff) when the vehicle is a RHD market vehicle. It also moves the doors views to the right side.
A bit of cleanup was also done on the battery view names and the autopilot icon logic.
Tested with mock server setting driverOrientation to 2f
> Create horizontal constraints helper for easily mirroring view placement

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/EfficiencyCalculator.kt
A few minor tweaks:
- require a long-press to reset min/max power values (instead of short press)
- show an info toast for any UI tap action describing what that action just did
- hide the instant efficiency text if speed is 0, to prevent "infinity kWh/mi"
> Long press to reset min-max power and more

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
In 2023.12 the bits were moved around for the dcdc frame. This only affects the party-mode dash.
> Update 12v dc can signals for 2023.12

- android/app/src/main/java/app/candash/cluster/Constants.kt
- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/FullscreenActivity.kt
- android/app/src/main/java/app/candash/cluster/PartyFragment.kt
- android/app/src/main/java/app/candash/cluster/SettingsFragment.kt
- android/app/src/main/res/layout/fragment_dash.xml
- android/app/src/main/res/layout/fragment_settings.xml
This fixes a bug from June where the display sync pref was inverted (partially), causing the behavior to be inverted in party mode, and also causing the screen-on behavior to be inverted (with display sync, it should keep the screen on even when not plugged in, until low battery).
The fix entails renaming the pref to be representative of what it does.
Renaming the pref ensures:
- that existing users have the pref reset to default rather than invert to the opposite of what they set (arguably worse)
- that if any usages of the old pref was missed, a build error would make it obvious.
- that the code reads logically by naming the pref a name which represents what it actually is, not the inverse.
- ensured the display blanking behavior matched the preference in both dash and party mode
- …
> Fix partially inverted display sync pref

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
A bug exists where if AHB (auto-highbeam) is disabled in the UI, while using autopilot the standby icon doesn't show in candash despite it showing on the center display.
This is because the onboard logic changed at some point in the last year:
Before: disabling AHB in the UI while on autopilot would allow manual HB control, even in AP.
Now: AHB cannot be disabled in the UI while on autopilot, only can be temporarily disabled using the stalk.
Now it is enough to just look at the HB-request signal, which simplifies the logic.
> Fix AHB logic for showing AHB standby telltale

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
The BSW flash would basically latch on since we only listened for changes to the BSM signal and not also changes to the turn signal.
This fixes that and and tweaks the flash speeds a bit to make l1 vs l2 more obvious.
> Fix BSW false positive bug

- android/app/src/main/java/app/candash/cluster/CANSignalHelper.kt
Tested via log replays of old (< 2023.44.30) and new (202344.30.2) firmware logs.
Something has changed about the signals, but until we get new DBCs, we don't know how to properly decode the signal yet.
However with the current decoding, it appears that while TACC is active, the value remains at 102.2 (with some FP rounding error)
> Hacky fix for TACC active icon on 2023.44.30

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/res/drawable/bsm_gradient.xml
- android/app/src/main/res/layout/fragment_dash.xml
Since level 1 BSW is now a little over-zealous, this PR makes level 1 a static (non-flashing) gradient when the turn signal is on, to match the OEM gradient in the camera view.
In my testing so far, level 1 always appears with a gradient in the camera, so by switching from the flash to static gradient, the BSW behavior should perfectly match that on the center display.
This change is separate from BSM arcs, if arcs are disabled, the gradient still shows when the turn signal is on. If arcs are enabled, you'll see see both the arcs and the gradient when the signal is on. The gradient never shows when the signal is off.
> Use static gradient for L1 BSW to match OEM

- android/app/src/main/java/app/candash/cluster/BatteryGauge.kt
- android/app/src/main/res/drawable/ic_autopilot.xml
- android/app/src/main/res/drawable/ic_deadbattery_night.xml
- android/app/src/main/res/drawable/ic_tacc.xml
- android/app/src/main/res/values/colors.xml
I'm not sure if because it changed recently, but I noticed the autopilot blue on the car is a lighter color (verified by peaking) than what we were using in candash.
Also, due to the cybermode pr, we lost the tinting of the battery background, causing it to be the wrong color.
This tweaks the autopilot blue, and adds the correct battery background colors (and new drawable so that tinting is not needed).
> Fix battery and autopilot colors

- android/app/src/main/res/values-night/themes.xml
- android/app/src/main/res/values/themes.xml
This fixes the crash on startup for android 8.0 and below.
The crash was caused by missing style attribute values since they were not defined in the pre-v27 theme file.
This also adds them to the night theme file although I'm not certain it's needed anywhere, but to be safe.
> Update theme files to support older api levels

- android/app/src/main/res/values/colors.xml
A partial revert of the recent autopilot blue change which ended up being too dark compared to oem.
Turns out the blue used on the wheel icon is lighter than the blue used elsewhere, and I grabbed the wrong value.
> Fix autopilot blue

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
When loading dash fragment while already in splitscreen, the savedLayoutParams map was never populated, and thus when downstream logic attempted to use that map, it would crash.
There's no reason not to save the initial layout params even while in splitscreen, it only saves on initial view creation so it's guaranteed to be the original layout params for each view, before the splitscreen listener modifies them.
Tested by putting app in splitscreen, then going to info fragment and back to dash fragment (recreated crash before this change, no crash after this change, view margins are still correctly modified)
> Fix crash when dash fragment loads in splitscreen

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
Since the efficiency text now shows at 0 speed, it needed to be added to the drivingViews so that it's hidden while charging, otherwise it interferes with the charging circle gauge.
> Hide efficiency while charging

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
An edge case can occur when candash (re)starts while charging, if it receives the power signal before the charge status signal, it can momentarily update minpower with the value caused by charging.
This fixes it by only saving minpower while gearstate is in drive or reverse...this means that even if we're missing the gear signal, it won't save (failsafe, as not updating minpower when unsure is better).
> Fix minpower from DCFC edge case

- android/app/src/main/java/app/candash/cluster/BatteryGauge.kt
- android/app/src/main/res/drawable/ic_deadbattery.xml
- android/app/src/main/res/values/colors.xml
A small visual tweak to fix the margins between the battery background and fill, and to add rounded corners to the fill. It also fixes the edge of the cap being clipped.
This now matches the oem icon much more closely.
> Fix battery margins to better match the original battery icon

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/EfficiencyCalculator.kt
- android/app/src/main/java/app/candash/cluster/EfficiencyChart.kt
- android/app/src/main/java/app/candash/cluster/SettingsFragment.kt
- android/app/src/main/res/layout/fragment_settings.xml
A few minor tweaks based on user feedback:
- Adjust gradient opacity to make the zero line less distracting
- Also move the gradient position closer to the line, now the gradient is equal on both pos and neg sides of the line
- Fix a bug causing the pos and neg lines to overlap slightly when crossing the zero line
- Mostly noticeable in the fragment preview, but visible IRL when looking closely.
- Move chart toggle to settings fragment, and change efficiency long-press to toggle chart instead of reset efficiency
- Chart visibility depends on efficiency visibility, so the settings checkbox behavior reflects that dependency.
- The settings fragment layout was adjusted slightly to accommodate the extra checkbox, as the middle column was crowded
- Removed "Long-press screen when display off" …
> Efficiency graph updates

- android/app/src/main/java/app/candash/cluster/MockCANService.kt
- android/app/src/main/java/app/candash/cluster/PartyFragment.kt
In digging into a seemingly buggy permissions prompt (it seemed that some api levels didn't require permission, or even would crash when attempting to request permission) I was unable to reproduce the need to request permission on any api level for the alarm to work.
This removes the entire permission request flow, adds a party option to the mock server to make it easier to test party mode, and a couple of other minor improvements in the party alarm update logic.
> Remove unnecessary permission prompt for party alarm

- android/app/src/main/java/app/candash/cluster/DashFragment.kt
- android/app/src/main/java/app/candash/cluster/DashViewModel.kt
- android/app/src/main/java/app/candash/cluster/FullscreenActivity.kt
- android/app/src/main/java/app/candash/cluster/InfoFragment.kt
- android/app/src/main/java/app/candash/cluster/PartyFragment.kt
- android/app/src/main/java/app/candash/cluster/SettingsFragment.kt
On first install (and any time the app is started while connected to the wrong service, such as mock service), the activity is not listening to the correct signals to update brightness and theme, causing it to not update brightness or theme when the car updates.
This is because the fullscreen activity listens to carState upon startup, and can't (easily) be changed to listen to a new carState when the service changes.
To get around this issue, we move theme and brightness listener ownership back into each fragment, as the fragments are recreated upon changing the service. To reduce code duplication, the viewModel hosts the theme and brightness listener code. The fragments trigger the activity to update via a viewmodel livedata boolean, as the theme and brightness updates are handled by the …
> Move brightness and theme listener ownership to fragments
